[package]
name = "acpplinter"
version = "0.1.0"
authors = ["Tommaso Checchi <tommaso.checchi1@gmail.com>"]

[dependencies]
regex = "*"
rustc-serialize = "*"
regex_macros = "*"
threadpool = "*"
num_cpus = "*"
clap = "*"